apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 3000    # Should match the containerPort
      nodePort: 30007     # Optional: specify or let Kubernetes auto-assign
