replicaCount: 2

image:
  repository: disidesh/signiance
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080  

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: signiance.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

secretEnvs:
  - name: AWS_ACCESS_KEY_ID
    secretKeyRef:
      name: aws-secrets
      key: aws_access_key_id

  - name: AWS_SECRET_ACCESS_KEY
    secretKeyRef:
      name: aws-secrets
      key: aws_secret_access_key
